- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks:
  - name: greating
    ansible.builtin.debug:
      msg: "hi ankitha, {{ GREATING | default('good morning') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"   

  - name: convert list to map  
    ansible.builtin.debug:
      msg: "{{ tagslist | items2dict }} 